### ISSUE TITLE
docker-compose up -d --build is failing

### ISSUE THREAD

**Issue by matifayaz** [Epse/EpPos#68]
I've Installed docker and docker-compose, downloaded **EpPos** and navigated into the directory. Now when I run `docker-compose up -d --build`, it fails giving the following messages and errors:

Building web
Step 1/3 : FROM python:3.5-onbuild
# Executing 3 build triggers...
Step 1/1 : COPY requirements.txt /usr/src/app/
 ---> Using cache
Step 1/1 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Using cache
Step 1/1 : COPY . /usr/src/app
 ---> Using cache
 ---> 2f0952866368
Step 2/3 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 6887784cd6b3
Step 3/3 : RUN python manage.py migrate
 ---> Running in 2b5f4d83629e
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
ERROR: Service 'web' failed to build: The command '/bin/sh -c python manage.py migrate' returned a non-zero code: 1
![screenshot from 2018-10-09 19 55 10](https://user-images.githubusercontent.com/7438507/46678082-4e8fa000-cbfd-11e8-830c-bc82679cbace.png)
![screenshot from 2018-10-09 19 54 08](https://user-images.githubusercontent.com/7438507/46678083-4f283680-cbfd-11e8-9db7-875d0e71acdc.png)

**Comment by ZeroCoolHacker** [comment]
1. Make sure you have the permission to create files/folders
2. Create a directory 'db' in web folder manually and try again

**Comment by Epse** [comment]
Yeah that's what you get when there isn't a `db` folder.. I'll look into a way of forcing the existence of that folder

**Comment by Epse** [comment]
So, I don't know what system you are on, but here's the short version:
1. Go to wherever you have the EpPos source stored
2. Open the folder named `web`
3. Create an empty folder named `db`
4. Rerun `docker-compose`

This should fix your issue. If it does, please let me know so I can close this.
For the future, #71 will create that folder behind-the-scenes for you when building the Docker image.

**Comment by matifayaz** [comment]
Thank you @ZeroCoolHacker & @Epse for the swift response and help. After creating **db** folder in **web**, it's working now.

Thanks

**Comment by Epse** [comment]
Alright, then I'm closing this! Happy to help!
